CREATE TABLE torrent_files
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    torrent_id      BIGINT                                  NOT NULL,
    path            VARCHAR(255)                            NOT NULL,
    size            BIGINT                                  NOT NULL,
    downloaded_size BIGINT,
    progress        DOUBLE PRECISION,
    priority        INTEGER,
    CONSTRAINT pk_torrent_files PRIMARY KEY (id)
);

ALTER TABLE torrent_files
    ADD CONSTRAINT FK_TORRENT_FILES_ON_TORRENT FOREIGN KEY (torrent_id) REFERENCES torrents (id);